rishabh-bansal/C-Data-Structures-and-Algorithms

Searching problems/BINARY_SEARCH.cpp
Searching problems/LINEAR_SEARCH.cpp

linear search  - added
binary search - added

Added SearcingProblems

---

Sorting/Heapsort.cpp
Sorting/bubblesort.c
Sorting/bucketsort.cpp
Sorting/insertionsort.cpp
Sorting/quicksort.c
Sorting/radixsort.cpp
Sorting/selectionsort.c

Sorting Algorithms

---

Searching Techniques/MEDIAN_SEARCH.cpp

Median Search usually used for finding Kth Smallest or Kth Largest Element in an array.
Complexity - O(n)

Median Search

---

Tree Problems/TREE.cpp

1.Insert Element 
2.Delete Element 
3.Inorder Traversal
4.Preorder Traversal
5.Postorder Traversal
6.Display
7.Quit

Tree implementation in c++ 

---

Sorting/count_sort.c

count_sort.c file added in sorting folder

Add count_sort.c

---

Patterns/pattern1.cpp

Updated pattern1.cpp to add comments

---

Patterns/pattern2.cpp

Updated pattern2.cpp

---

Patterns/pattern3.cpp

Updated pattern3.cpp

---

Patterns/pattern7.cpp

Added inline comments to pattern7

---

BINARY_SEARCH_TREE.cpp

Binary Search Tree code implementation added. issue #1

Binary Search Tree added.

---

.gitignore
Stack/Stack.cpp

Implemented stacks using arrays in cpp.

Added Stack Implementation

---

countingsort.cpp
dfs.c

This searching algorithm uses adjacency matrix.

depth_first_search

---

Searching problems/ternarySearch.cpp

Ternary Search code added

---

xorlist.c

Memory Efficient doubly linked list using the XOR list technique. solving issue #2

memory efficient dll or XOR List Code added

---

Graph Programs/graph_adjacency_list.cpp
Graph Programs/graph_adjacency_matrix.cpp
Graph Programs/graph_topological_sort.cpp

Graph Programs added as mentioned in Issue #31

Solution to Issue #31

---

Sorting/bucketsort.cpp

The current version of the bucket sort uses C style arrays and index based for loops.
This commit modifies the bucket sort algorithm to use modern C++ features such as vectors and range based for loops as well as auto for
type specifiers.
Furthermore, the `using namespace std;` line has been removed as it is generally considered a bad practice.

Rewrote bucket sort to use modern C++

---

Stack/largestRectangleHistogram.cpp

Stack implementation for largest area rectangle in histogram

---

Graph Programs/graph_bfs.cpp
Graph Programs/graph_dfs.cpp
Graph Programs/graph_kruskals_algorithm.cpp

BFS, DFS, Implementation of Kruskal's algorithms added.

Graph Programs added

---

Graph Programs/bfs.c
Graph Programs/dfs.c
LinkedList/DLL.cpp
LinkedList/SLL.cpp
LinkedList/xorlist.c
Queue/queue.c

- Created a new Directory for LinkedList programs.
- Refactored bfs to bfs.c
- Moved bfs.c & dfs.c to Graph Programs directory

Organised LinkedList code to directory & refoactored Graph Programs

---

Graph Programs/dijkstra.cpp

Added Dijkstra Algorithm in Graph Problems.

---

Backtracking/NQueens.c

Added a classic backtracking problem i.e `NQueens` problem

Added Backtracking Problems #NQueens

---

Patterns/invertedtreepattern.cpp
Patterns/treepattern.cpp

Added New patterns with comments in C

Added New patterns in c

---

hackt.cbp
main.c

using nested loops printing the pattern

The star pattern output program

---

Backtracking/KnightTour.c

Added a classical backtracking problem i.e Knight Tour Problem.

Added Knight Tour Problem

---

unionarray.c

we can enter size of both the arrays and insert elements in both the arrays and we will get union of them

union of two arrays

---

lucky 7 game.c

program will generate a random no. between 1 and 14. User will enter a certain amount. user will select one of the 3 options i.e below 7, on 7, above 7. if he select 1st or 3rd option and he get rights his amount gets doubled or if he selects 2nd option his amount will be tripled but  if he select wrong option his amount will be lost.

Lucky 7 Game
